
AllCops:
  NewCops: disable

plugins:
  - rubocop-rails

Layout/LineLength:
  Max: 200

Layout/HashAlignment:
  EnforcedColonStyle: table

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - valet_dev
    - valet_test
    - valet_prod

# What do we want to ignore?
Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/Not:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false





